[package]
name = "auto-ipld"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
cid = { version = "0.8.4", features = ["serde-codec"] }
serde = "1.0.136"
